# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qws.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'qws.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tqws.proto\x12\x03qws\"=\n\x0c\x41uthenticate\x12\x0e\n\x06msg_id\x18\x01 \x01(\r\x12\x10\n\x08msg_date\x18\x02 \x01(\x04\x12\x0b\n\x03jwt\x18\x03 \x01(\t\"N\n\tSubscribe\x12\x0e\n\x06msg_id\x18\x01 \x01(\r\x12\x10\n\x08msg_date\x18\x02 \x01(\x04\x12\r\n\x05proto\x18\x03 \x01(\r\x12\x10\n\x08\x63hannels\x18\x04 \x03(\x0c\"l\n\x0c\x43loudPayload\x12\x0e\n\x06msg_id\x18\x01 \x01(\r\x12\x10\n\x08msg_date\x18\x02 \x01(\x04\x12\r\n\x05proto\x18\x03 \x01(\r\x12\x0b\n\x03src\x18\x04 \x01(\x0c\x12\r\n\x05\x64\x65sts\x18\x05 \x03(\x0c\x12\x0f\n\x07payload\x18\x07 \x01(\x0c\"M\n\x0c\x45rrorMessage\x12\x0e\n\x06msg_id\x18\x01 \x01(\r\x12\x10\n\x08msg_date\x18\x02 \x01(\x04\x12\x0c\n\x04\x63ode\x18\x03 \x01(\r\x12\r\n\x05\x64\x65scr\x18\x04 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qws_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHENTICATE']._serialized_start=18
  _globals['_AUTHENTICATE']._serialized_end=79
  _globals['_SUBSCRIBE']._serialized_start=81
  _globals['_SUBSCRIBE']._serialized_end=159
  _globals['_CLOUDPAYLOAD']._serialized_start=161
  _globals['_CLOUDPAYLOAD']._serialized_end=269
  _globals['_ERRORMESSAGE']._serialized_start=271
  _globals['_ERRORMESSAGE']._serialized_end=348
# @@protoc_insertion_point(module_scope)
