#!/bin/sh
set -e
VENVDIR="/opt/kalinka/venv"
INSTALLDIR="/opt/kalinka/wheels"
WHEEL="${INSTALLDIR}/kalinka_plugin_qobuz-@VERSION@-py3-none-any.whl"

if [ ! -x "$VENVDIR/bin/pip" ]; then
  echo "Kalinka venv not found at $VENVDIR" >&2
  exit 1
fi

"$VENVDIR/bin/pip" install --upgrade "$WHEEL"

exit 0